### ISSUE TITLE
Lỗi  liên quan đến việc chuyển một trường nhập liệu giữa hai trạng thái uncontrolled và controlled trong React

### ISSUE THREAD

**Issue by nguyenthiyenly0407** [ngodat0103/se347#102]
![image](https://github.com/user-attachments/assets/6ccea9d5-3cc1-49c2-ace0-efcfaa3c2695)

**Comment by ngodat0103** [comment]
Coi thử xem nó là gì và fix được không

**Comment by nguyenthiyenly0407** [comment]
@ngodat0103  ok

**Comment by VietDucc** [comment]
da fix xem pull resquest

**Comment by VietDucc** [comment]
Có lỗi thì fix đi đã, ko được hãy tạo issua @nguyenthiyenly0407
