### ISSUE TITLE
Đổi hết tên Jira trong project

### ISSUE THREAD

**Issue by SuperCoolGuy855** [ngodat0103/se347#107]
Ai có ý kiến thay bằng tên gì thì ghi vào đây.

**Comment by ngodat0103** [comment]
![image](https://github.com/user-attachments/assets/3f8287cb-77d8-4a57-b890-ffabdfd503ed)

**Comment by VietDucc** [comment]
![image](https://github.com/user-attachments/assets/6a87c47a-e624-49fd-888a-5ddb0ff9d9f2)
đổi logo đổi tên là Navi
