### ISSUE TITLE
[Frontend]: Thống nhất về việc dùng thư viên lấy gọi API

### ISSUE THREAD

**Issue by ngodat0103** [ngodat0103/se347#116]
Bruh, có thể thống nhất một cái được không, có mỗi lấy API mà nhóm mình dùng tận 3 dạng rồi ấy
Fetch, ReactQuery + fetch, axios?

_Originally posted by @ngodat0103 in https://github.com/ngodat0103/se347/pull/115#discussion_r1899053564_

**Comment by VietDucc** [comment]
code đang chạy mà sửa là lỗi đó
