### ISSUE TITLE
Suppress lỗi khi join workspace mà đã join workspace trước đó

### ISSUE THREAD

**Issue by SuperCoolGuy855** [ngodat0103/se347#121]
https://github.com/user-attachments/assets/20a14dac-dffe-4865-b442-3a955b536948

**Comment by ngodat0103** [comment]
@nguyenthiyenly0407 Coi thử xem fix được không

**Comment by nguyenthiyenly0407** [comment]
@ngodat0103 ok

**Comment by VietDucc** [comment]
![image](https://github.com/user-attachments/assets/b58df455-be69-4f4f-8760-49a36b562507)

**Comment by VietDucc** [comment]
![image](https://github.com/user-attachments/assets/adf46cd4-61f8-4be5-84cd-3954fc1b0022)
- M là người tạo mà còn tham gia vô nó bảo m là chủ đúng rồi chứ sai gì

**Comment by VietDucc** [comment]
@SuperCoolGuy855  xem rồi close I

**Comment by SuperCoolGuy855** [comment]
> ![image](https://private-user-images.githubusercontent.com/169456748/399421921-adf46cd4-61f8-4be5-84cd-3954fc1b0022.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2MjgxOTMsIm5iZiI6MTczNTYyNzg5MywicGF0aCI6Ii8xNjk0NTY3NDgvMzk5NDIxOTIxLWFkZjQ2Y2Q0LTYxZjgtNGJlNS04NGNkLTM5NTRmYzFiMDAyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMVQwNjUxMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTFiZGE1YzM4ZDIwMDgyMTljMzViNGZiN2FjMWMxZTc5ZmFkOGQ2MjQwMmNmMWI2ZGFhZWRhNWE1OWVmMWMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.--1uci5PK_01BGwVdI_BXgWV7pjnRPNmT5R2tc6pP3s)
> 
>     * M là người tạo mà còn tham gia vô nó bảo m là chủ đúng rồi chứ sai gì
Có thèm coi video t đính kèm theo ko vậy? T đâu có nói là cái thông báo đó. Cái lỗi ở phía dưới á nhóc.

**Comment by nguyenthiyenly0407** [comment]
![image](https://github.com/user-attachments/assets/c70e7359-8cfa-4035-b956-e7860481af41)
là kiểu này hả? 
@SuperCoolGuy855 mất 2 cái error dưới
