### ISSUE TITLE
[Frontend/Backend]: Không chuyển task sang project khác được

### ISSUE THREAD

**Issue by SuperCoolGuy855** [ngodat0103/se347#127]
https://github.com/user-attachments/assets/e286129a-2d77-4a34-a287-b6e8cf6b87e3

**Comment by ngodat0103** [comment]
mở trong cái response Body, cái gì not found

**Comment by SuperCoolGuy855** [comment]
![image](https://github.com/user-attachments/assets/3554581f-d3ce-4b72-b00d-e955f2714cc3)
