### ISSUE TITLE
Tasks không cập nhật đúng khi đổi trong kanban

### ISSUE THREAD

**Issue by SuperCoolGuy855** [ngodat0103/se347#130]
https://github.com/user-attachments/assets/d9a4d091-7aab-4871-be8d-3dc003d796ed

**Comment by SuperCoolGuy855** [comment]
Thấy edit task thì lại cập nhật đúng nè, coi thử nó cập nhật sao, copy giống vậy được ko.

**Comment by SuperCoolGuy855** [comment]
https://github.com/user-attachments/assets/650eaab2-58a8-4e00-8da4-0885ba68b469

**Comment by VietDucc** [comment]
trời ơi qua bên kia 
thì phải reload hai component sao là dùng useState được Minh

**Comment by VietDucc** [comment]
mấy web lớn cũng v mà

**Comment by VietDucc** [comment]
cập nhật động đó là dùng useState mà useState làm sao dùng cho cả hai component được

**Comment by SuperCoolGuy855** [comment]
table cập nhật động được đó

**Comment by VietDucc** [comment]
table động qua bên kaban ko

**Comment by VietDucc** [comment]
ok hiểu cách hoạt động r
