### ISSUE TITLE
[Frontend]: Thiếu chức năng Open Project

### ISSUE THREAD

**Issue by ngodat0103** [ngodat0103/se347#134]
![image](https://github.com/user-attachments/assets/7f0080f6-4c3f-48ae-b5e0-90f50d4a989c)

**Comment by VietDucc** [comment]
![image](https://github.com/user-attachments/assets/d477fd85-8209-495d-828d-555f3cca1046)
lỗi ở đâu? open project thì nó mở lên cái trang này đúng r cu 
![image](https://github.com/user-attachments/assets/70ff6277-01d6-4413-91dc-13062de6f0b3)

**Comment by ngodat0103** [comment]
> ![image](https://private-user-images.githubusercontent.com/169456748/399423492-d477fd85-8209-495d-828d-555f3cca1046.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NTczMjYsIm5iZiI6MTczNTY1NzAyNiwicGF0aCI6Ii8xNjk0NTY3NDgvMzk5NDIzNDkyLWQ0NzdmZDg1LTgyMDktNDk1ZC04MjhkLTU1NWYzY2NhMTA0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMVQxNDU3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTBlOTViNTZlMDY3NDc4MzgzMDAxN2U4YzIyNjNkZTc4Mjc2ZDRhZmNlMGYwODAzYWU4MTU0MWUxNzBlOWE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2GI_FnvJrggrXWX0LmhtguPykySceXDp7GBS0TUrCy0) lỗi ở đâu? open project thì nó mở lên cái trang này đúng r cu ![image](https://private-user-images.githubusercontent.com/169456748/399423547-70ff6277-01d6-4413-91dc-13062de6f0b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NTczMjYsIm5iZiI6MTczNTY1NzAyNiwicGF0aCI6Ii8xNjk0NTY3NDgvMzk5NDIzNTQ3LTcwZmY2Mjc3LTAxZDYtNDQxMy05MWRjLTEzMDYyZGU2ZjBiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMVQxNDU3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWVkZmQ3N2YxNzJhNGIwYzk4YTdjZTlhNTlmZjJmNzU5N2Q2NzQ2ZDA0NWYxNWY4NmNiODQ2Y2NjZWRkZWIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.waPYCF7ntedRNgBW-UPhpwNJPM4Cs3JQgzbG-GWAlx4)




nó có render đâu ? 

https://github.com/user-attachments/assets/7a52f538-3560-48ba-85e5-f48ce5f27192

Với lại này đâu phải lỗi
