### ISSUE TITLE
Thêm notification vào edit profile

### ISSUE THREAD

**Issue by SuperCoolGuy855** [ngodat0103/se347#137]
Nhờ thêm thông báo chỉnh sửa thành công hoặc bị lỗi vào page edit profile

**Comment by SuperCoolGuy855** [comment]
Và tải lại trang hoặc làm cách nào đó để top bar thay đổi theo khi cập nhật thành công.

![image](https://github.com/user-attachments/assets/0be85967-e211-41cb-aa25-a9f61d45dbe1)

**Comment by VietDucc** [comment]
@nguyenthiyenly0407

**Comment by nguyenthiyenly0407** [comment]
https://github.com/user-attachments/assets/83bb5b64-224c-445f-a993-73ad89b09618

kiểu vầy hả?
@VietDucc

**Comment by SuperCoolGuy855** [comment]
> Ghi.man.hinh.1.online-video-cutter.com.mp4
> 
> kiểu vầy hả? @VietDucc

Thấy ok đó! Push lên để kiểm thử.

**Comment by nguyenthiyenly0407** [comment]
> > Ghi.man.hinh.1.online-video-cutter.com.mp4
> > kiểu vầy hả? @VietDucc
> 
> Thấy ok đó! Push lên để kiểm thử.

ok
