### ISSUE TITLE
bản build với production mode bị lỗi logic, do thành phần middleware bước kiểm tra jwt token là server side, nó tự call 127.0.0.1:5000 bên phía server thay vì từ phía client(browser)

### ISSUE THREAD

**Issue by ngodat0103** [ngodat0103/se347#147]
Bản build với production mode bị lỗi logic, do thành phần middleware bước kiểm tra jwt token là server side, nó tự call 127.0.0.1:5000 bên phía server thay vì từ phía client(browser)
_Originally posted by @ngodat0103 in https://github.com/ngodat0103/se347/issues/146#issuecomment-2566323328_

**Comment by SuperCoolGuy855** [comment]
@ngodat0103
Không hiểu đang nói lỗi gì cả. Là bị lỗi logic gì?

**Comment by ngodat0103** [comment]
> @ngodat0103 Không hiểu đang nói lỗi gì cả. Là bị lỗi logic gì?

https://github.com/user-attachments/assets/f4eabaf4-7ded-40b2-ac44-3a0b2cfddfd4

nói tóm lại nếu cái jwt validate nó call api verify bên phía server frontend, tự call chính nó nên không build production với ip là 127.0.0.1 để demo được

**Comment by ngodat0103** [comment]
![image](https://github.com/user-attachments/assets/4e5aee2a-5d57-4e6e-8cde-1ad40deac547)
Cái hàm nàynày, có cách nào làm nó bên client (browser không), vấn đề là chỗ này, t dùng "use client" không được

**Comment by ngodat0103** [comment]
Xử lý bằng cách add host
