### ISSUE TITLE
Thêm tất cả router bảo vệ tuyến đường khi ko có token ở mỗi page.tsx 

### ISSUE THREAD

**Issue by VietDucc** [ngodat0103/se347#148]

**Comment by SuperCoolGuy855** [comment]
Cần bảo vệ route nào? Thêm vào middleware á.

Middleware đang chạy theo whitelist, là route nào đc ghi vào mới đc bảo vệ thôi.

**Comment by VietDucc** [comment]
test thử đăng xuất rồi nhấn quay lại xem có quay về login ko hay nó vẫn ở đó render ra cái giao diện luôn

**Comment by SuperCoolGuy855** [comment]
OK ko?

https://github.com/user-attachments/assets/f48ee613-debe-48dc-bd34-c8566500c6fd

**Comment by VietDucc** [comment]
OK rồi
