### ISSUE TITLE
Không thể edit profile nếu không trong workspace

### ISSUE THREAD

**Issue by SuperCoolGuy855** [ngodat0103/se347#151]
![image](https://github.com/user-attachments/assets/f42713a3-2f45-4bdd-a498-d2bc6558f521)

@nguyenthiyenly0407 giải thích code này được ko? Tại sao lại có code này? Tại sao phải kiểm tra có workspaceID?

**Comment by nguyenthiyenly0407** [comment]
hướng của ly là tạo workspace trước rồi mới chỉnh profile. tại mới dô tạo workspace trước

**Comment by nguyenthiyenly0407** [comment]
mà nếu bỏ workspaceid thì bỏ thôi

**Comment by nguyenthiyenly0407** [comment]
> ![image](https://private-user-images.githubusercontent.com/29012883/399479006-f42713a3-2f45-4bdd-a498-d2bc6558f521.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NTM1NjUsIm5iZiI6MTczNTY1MzI2NSwicGF0aCI6Ii8yOTAxMjg4My8zOTk0NzkwMDYtZjQyNzEzYTMtMmY0NS00YmRkLWE0OTgtZDJiYzY1NThmNTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMxVDEzNTQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2NzM4ZmE1ZGI2NjE1Y2Y1YmJjNTVkYzg0NWI0OTYxM2JkNTAyYzkwN2QxNjc3Njc1MWU2Y2I0Y2UxY2FhNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Tpa_42D_9WS5QDBBhPH1B5g2RB9d-1JSexdr_1b6JkY)
> 
> @nguyenthiyenly0407 giải thích code này được ko? Tại sao lại có code này? Tại sao phải kiểm tra có workspaceID?

rồi nhé, ly bỏ workspaceid trong hàm rồi đó check ik
