### ISSUE TITLE
Căn giữa nút edit profile

### ISSUE THREAD

**Issue by SuperCoolGuy855** [ngodat0103/se347#152]
![image](https://github.com/user-attachments/assets/7d7ef616-b8e3-420e-aefd-4ab8daf51f90)

**Comment by nguyenthiyenly0407** [comment]
> ![image](https://private-user-images.githubusercontent.com/29012883/399480823-7d7ef616-b8e3-420e-aefd-4ab8daf51f90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NTM2MDgsIm5iZiI6MTczNTY1MzMwOCwicGF0aCI6Ii8yOTAxMjg4My8zOTk0ODA4MjMtN2Q3ZWY2MTYtYjhlMy00MjBlLWFlZmQtNGFiOGRhZjUxZjkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMxVDEzNTUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiZDA3NGI5NjUwNjJmNTlhYmRhMGY3NmVkODIzZGU2MzA4OGQ0MDQ2ODIyYmVkNDJiODBmMTBkODhjMTkxYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.b-ZL6wPiMrvAEu95dP2qiJCQRabKD8vVC-frOZ4_VqA)

![image](https://github.com/user-attachments/assets/0d8955f3-c1b2-4e4a-8f97-ec8ea8698875)
done rồi nha
