### ISSUE TITLE
> Sao chưa đăng kí mà đã kêu có tài khoản rồi?

### ISSUE THREAD

**Issue by ngodat0103** [ngodat0103/se347#18]
> Sao chưa đăng kí mà đã kêu có tài khoản rồi?
> 
> ![image](https://github.com/user-attachments/assets/d391f1e1-7e50-493f-a9c9-b059c911c194)
> 
> 
> 
> Email validation vẫn còn dở, hình như ko đồng nhất với backend. Với lại nếu client-side validation bị lỗi thì báo lỗi cho user biết.
> 
> 
> 
> Đăng nhập sai cũng nên báo lỗi cho user biết.
> 
> 
> 
> Đăng nhập thành công thì lại bị response 2 lần, ko biết sẽ có bị gì ko
> 
> ![image](https://github.com/user-attachments/assets/dd8f6eed-ceb8-48e5-8ff7-f0ce978ecc3b)
> 
> 
> 
> Mà tạm thời chấp nhận đc.

fix lại hồi trưa rồi nhé mà chưa push

_Originally posted by @VietDucc in https://github.com/ngodat0103/se347/issues/13#issuecomment-2490273812_

**Comment by VietDucc** [comment]
![image](https://github.com/user-attachments/assets/585679c4-3e0b-432d-bc63-502d9d4771d0)

**Comment by VietDucc** [comment]
đang fix lại hiện thông báo cho người dùng lỗi trả về

**Comment by SuperCoolGuy855** [comment]
Sửa ở đâu ko thấy nhỉ? Trên branch dev là t chưa thấy.

**Comment by VietDucc** [comment]
![image](https://github.com/user-attachments/assets/24a0ebfa-a45f-4df7-a754-6a60830cc9d4)
ở nhánh vietduc/fix

**Comment by SuperCoolGuy855** [comment]
> ```
>           > Sao chưa đăng kí mà đã kêu có tài khoản rồi?
> ```
> 
> > ![image](https://private-user-images.githubusercontent.com/29012883/388391231-d391f1e1-7e50-493f-a9c9-b059c911c194.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNzE4MDgsIm5iZiI6MTczMjM3MTUwOCwicGF0aCI6Ii8yOTAxMjg4My8zODgzOTEyMzEtZDM5MWYxZTEtN2U1MC00OTNmLWE5YzktYjA1OWM5MTFjMTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDE0MTgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MjQyN2Q5MjkxMzMwYTIxYWJjMzE1ZTA5NTE2ODRmYmE3YWY4NDAxOWMwNmVhNzA2MmJlOGQyZjgwNWFhNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lQ6-LDVLjwWZB6qEmDuOk6rHw7pGprvYu2831ExGjnk)
> > Email validation vẫn còn dở, hình như ko đồng nhất với backend. Với lại nếu client-side validation bị lỗi thì báo lỗi cho user biết.
> > Đăng nhập sai cũng nên báo lỗi cho user biết.
> > Đăng nhập thành công thì lại bị response 2 lần, ko biết sẽ có bị gì ko
> > ![image](https://private-user-images.githubusercontent.com/29012883/388391343-dd8f6eed-ceb8-48e5-8ff7-f0ce978ecc3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNzE4MDgsIm5iZiI6MTczMjM3MTUwOCwicGF0aCI6Ii8yOTAxMjg4My8zODgzOTEzNDMtZGQ4ZjZlZWQtY2ViOC00OGU1LThmZjctZjBjZTk3OGVjYzNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDE0MTgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzYTU4MzYzZWJjN2I0NTc4ZTUzOGI5NjJmOWMwYzUyZWU5M2Q3Y2E0YmJhYjc5ZmU3YjJmYzQ5NGE2MDI5MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EdWsGTtX9rnSMQdJwQR6T4B4mMFnZ2SSEoHjxAMVi-4)
> > Mà tạm thời chấp nhận đc.
> 
> fix lại hồi trưa rồi nhé mà chưa push
> 
> _Originally posted by @VietDucc in [#13 (comment)](https://github.com/ngodat0103/se347/pull/13#issuecomment-2490273812)_

Fix này nè, có đọc ko vậy trời!

**Comment by SuperCoolGuy855** [comment]
@VietDucc 
![image](https://github.com/user-attachments/assets/787e4598-85c4-4315-be4f-7bf960b8dcb5)

**Comment by SuperCoolGuy855** [comment]
> @VietDucc ![image](https://private-user-images.githubusercontent.com/29012883/389203063-787e4598-85c4-4315-be4f-7bf960b8dcb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNzE5MzksIm5iZiI6MTczMjM3MTYzOSwicGF0aCI6Ii8yOTAxMjg4My8zODkyMDMwNjMtNzg3ZTQ1OTgtODVjNC00MzE1LWJlNGYtN2JmOTYwYjhkY2I1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDE0MjAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNjg0N2Y3OTFiNzQ1YmU5M2ExZjU5MGRmOWM0ODljZTk3ZmNmOWFkOGY5ODU4N2JjNDEyZDcxYjRmZWQxODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oVvvcFooXvVvgrgO-4A0TUEp1iLYPmAA-AH-dombALU)

Nếu người ta chưa có tài khoản thì sao lại ghi là có rồi?

**Comment by VietDucc** [comment]
? là sao

**Comment by VietDucc** [comment]
có sài web bao giờ chưa ba

**Comment by VietDucc** [comment]
nếu lỡ nhấn vô đăng ký mà có tài khoản r, thì nhấn log in để qua, còn nếu đăng ký thành công thì là đã có tk r, thì nhấn qua login

**Comment by VietDucc** [comment]
trải nhiệm người dùng web nào cũng v mà

**Comment by SuperCoolGuy855** [comment]
Bruh
![image](https://github.com/user-attachments/assets/1bc5291d-305c-4bb6-ad27-ae9b925fdcce)

Thấy bên login thì nó là câu hỏi ko? Nếu user chưa có thì hãy sign up.

![image](https://github.com/user-attachments/assets/00b2a141-d225-4cfe-83e1-7dcdb781afaa)
Còn này là câu khẳng định, khẳng định rằng user đã có tài khoản rồi, chỉ cần login thôi. Vậy là sai chứ gì nữa.

Ý là sửa lại đúng từ ngữ đi.

**Comment by ngodat0103** [comment]
![image](https://github.com/user-attachments/assets/a8773f48-ee31-4617-ac8a-ea94d4518681)
Copy luôn chính chủ cho nhanh

**Comment by VietDucc** [comment]
ok lấy luôn đó

**Comment by VietDucc** [comment]
![image](https://github.com/user-attachments/assets/a13c930f-8a3f-4971-8d75-c28e12d0da15)
Done
