### ISSUE TITLE
Login-sign up

### ISSUE THREAD

**Issue by VietDucc** [ngodat0103/se347#20]
![image](https://github.com/user-attachments/assets/572a6e17-bdf0-433c-b550-7ffaba05769a)
Trả lỗi về vậy 
Mà chưa có api signup à @ngodat0103 
Đăng ký rồi mới tới đăng nhập chứ

**Comment by ngodat0103** [comment]
Có Api signup mà friend
![image](https://github.com/user-attachments/assets/00a974bd-5f54-4d77-bdfb-2acc69aee8fd)

**Comment by VietDucc** [comment]
Đăng ký là lưu thông tin người dùng luôn, rồi đăng nhập, thấy cu long làm có dánh sách user trên cái swager luôn, vậy là database làm sau à hay sao

**Comment by ngodat0103** [comment]
Danh sách users, code cũng được thôi nhưng mà chi, m có trang nào cần list hết toàn bộ user trong database à?
Còn muốn lấy thông tin database thì mốt t nhắn riêng credential cho
> Đăng ký là lưu thông tin người dùng luôn, rồi đăng nhập, thấy cu long làm có dánh sách user trên cái swager luôn, vậy là database làm sau à hay sao

**Comment by VietDucc** [comment]
nhưng mà login sign up done rồi đk, qua dashboard nha

**Comment by ngodat0103** [comment]
Ok
