### ISSUE TITLE
thông báo đăng ký thành công, đăng ký failed ở page register

### ISSUE THREAD

**Issue by ngodat0103** [ngodat0103/se347#23]
thông báo đăng ký thành công, đăng ký failed ở page register

_Originally posted by @ngodat0103 in https://github.com/ngodat0103/se347/issues/22#issuecomment-2492850565_

**Comment by VietDucc** [comment]
![image](https://github.com/user-attachments/assets/3285994d-189d-4d22-b3ab-5876145ceff6)
Done!

**Comment by VietDucc** [comment]
![image](https://github.com/user-attachments/assets/551be345-e789-43ef-9e66-ee86bad9bbbc)
