### ISSUE TITLE
Logic Login: sau khi Login thành công, redirect đến page dashboard, chờ feature này

### ISSUE THREAD

**Issue by ngodat0103** [ngodat0103/se347#24]
Logic Login: sau khi Login thành công, redirect đến page dashboard, chờ feature này

_Originally posted by @ngodat0103 in https://github.com/ngodat0103/se347/issues/22#issuecomment-2492850250_

**Comment by VietDucc** [comment]
![image](https://github.com/user-attachments/assets/7b014b1a-b819-4ab8-98ef-2b11cc434d29)
Done!
