### ISSUE TITLE
Redirect từ register sang login khi register thành công

### ISSUE THREAD

**Issue by SuperCoolGuy855** [ngodat0103/se347#26]
Khi user tạo tài khoản thành công, nên redirect user sang login page để user đăng nhập luôn.

**Comment by VietDucc** [comment]
Thôi vậy được rồi người ta tự động nhấn sign in cho có trải nhiệm người dùng

**Comment by SuperCoolGuy855** [comment]
Làm đi, thấy website khác là có tự redirect mà.

**Comment by VietDucc** [comment]
DONE! Nha sếp( Nếu mà qua luôn mà còn bảo t làm cái thông báo đăng ký thành công, có nhìn kịp đâu)
