### ISSUE TITLE
Login và sign up đều không báo lỗi email validation đúng

### ISSUE THREAD

**Issue by SuperCoolGuy855** [ngodat0103/se347#28]
https://github.com/user-attachments/assets/74d3b323-ced5-49a6-bace-e063f6b3847c

Xem video.

Cả login và sign up đều bị. Coi lại thử xem fix đc ko?

**Comment by VietDucc** [comment]
bị gì v

**Comment by SuperCoolGuy855** [comment]
Nếu mà nhập email mà ko ghi `@xxx` gì đó vào thì nó lại ko báo lỗi á.

Muốn là nếu ko đúng format là email thì phải báo lỗi cho user biết, có @ hay ko gì cũng báo.

**Comment by VietDucc** [comment]
format emai dung la se nhu nao

**Comment by VietDucc** [comment]
bắt lỗi @ thôi chứ gm.uit.edu.vn outlook.com.vn sao biết mà bắt hết
