### ISSUE TITLE
Upload Image

### ISSUE THREAD

**Issue by VietDucc** [ngodat0103/se347#30]
![image](https://github.com/user-attachments/assets/21ad7132-28ef-4b3e-b713-fc3b19734e7f)
![image](https://github.com/user-attachments/assets/9bb52555-8960-474c-bc84-90ba0343b420)

**Comment by ngodat0103** [comment]
@VietDucc 
Có api upload image rồi nha
Limit size: 2MB
ACCEPT: PNG/JPEG
[Demo](https://youtu.be/89kZjjTMua4https://youtu.be/89kZjjTMua4)

**Comment by VietDucc** [comment]
![image](https://github.com/user-attachments/assets/66aa7b53-4c3a-4421-903d-34e9a34fb03f)
đổi lại server render ID cho workspace và lưu kiểu url image nha

**Comment by ngodat0103** [comment]
ý m là giữ cái đuôi file ảnh hay sao

**Comment by VietDucc** [comment]
t chỉ cần cái id thôi ảnh m lưu sao cũng được, mà bth là dùng url đó hay sao
