### ISSUE TITLE
Thiếu handle Exception trong trường hợp tạo cố tình tạo trùng workspace

### ISSUE THREAD

**Issue by ngodat0103** [ngodat0103/se347#36]
Chưa xử lý exception trong trường hợp cố tình tạo trùng workspace name trên cùng một tài khoản
![image](https://github.com/user-attachments/assets/f06104ad-7f0f-4173-989d-9c62214d12d5)

_Originally posted by @ngodat0103 in https://github.com/ngodat0103/se347/issues/27#issuecomment-2526267560_

**Comment by SuperCoolGuy855** [comment]
Tại sao này lại tag backend vậy?

**Comment by ngodat0103** [comment]
@VietDucc lỗi này frontend xử lí friend,backend t xong rồi

**Comment by VietDucc** [comment]
api trả về lỗi ko cho thêm chưa @ngodat0103

**Comment by ngodat0103** [comment]
![image](https://github.com/user-attachments/assets/81f1c444-cc13-4163-a7b3-72d843cf60f1)
chứ này là gì

**Comment by VietDucc** [comment]
sao hôm qua t vẫn tạo thành công

**Comment by ngodat0103** [comment]
> sao hôm qua t vẫn tạo thành công

vậy tí về xem lại đi

**Comment by VietDucc** [comment]
m kiểm tra thấy thành công hay thất bại nếu thất bại thì đúng r, khỏi kiểm tra tôi tin bạn

**Comment by ngodat0103** [comment]
![image](https://github.com/user-attachments/assets/c5c7522b-fc7e-4a8b-af2f-059aece92f46)
mêt m quá, mới thử này
