### ISSUE TITLE
Nên Refresh lại trang khi vừa tạo workspace

### ISSUE THREAD

**Issue by ngodat0103** [ngodat0103/se347#39]
Nên Refresh lại trang để cập nhật workspace mới vừa tạo
![image](https://github.com/user-attachments/assets/6d450e90-fcf7-4130-a70f-40a5f37d6c7a)

_Originally posted by @ngodat0103 in https://github.com/ngodat0103/se347/issues/27#issuecomment-2526294273_

**Comment by nguyenthiyenly0407** [comment]
![z6121352571524_b83ce25539378505766b72cb40b535f3](https://github.com/user-attachments/assets/ff783055-2937-4b66-b887-9466a0d1067d)
Tui có chỉnh cái đoạn Onsubmit thêm vô chỗ này và comment lại cái đoạn code của ông và push lên nhánh của tui rồi á, có gì vô coi thử nha, chứ tui ko chạy cái backend ko được nên chỉ dựa vào code thôi, nếu được thứ 7 ông bày tui chạy cái back lại

**Comment by ngodat0103** [comment]
> ![z6121352571524_b83ce25539378505766b72cb40b535f3](https://private-user-images.githubusercontent.com/127929336/394854754-ff783055-2937-4b66-b887-9466a0d1067d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NzAwMjIsIm5iZiI6MTczMzk2OTcyMiwicGF0aCI6Ii8xMjc5MjkzMzYvMzk0ODU0NzU0LWZmNzgzMDU1LTI5MzctNGI2Ni1iODg3LTk0NjZhMGQxMDY3ZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMlQwMjE1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjZmNzdmNTY4ZWM3NzZkM2IwZWYzY2U2MzI5MDMwNjg2MWU1MmQ5M2M2ZmE0MzgwZGQwNmVjZTk3Y2VkYmI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MIlNw7yePl96wp8rqLINwTlVfO3_mhXvb_Y3QQnDa5Y) Tui có chỉnh cái đoạn Onsubmit thêm vô chỗ này và comment lại cái đoạn code của ông và push lên nhánh của tui rồi á, có gì vô coi thử nha, chứ tui ko chạy cái backend ko được nên chỉ dựa vào code thôi, nếu được thứ 7 ông bày tui chạy cái back lại

backend t set up pipeline cho nó rồi, chỉ việc dùng thôi, t chưa viết docker compose mà một phát chạy lên hết do vẫn đang dev, nên tạm thời dùng luôn cái api t đang deploy đi
https://dev.se347.ngodat0103.live/

**Comment by ngodat0103** [comment]
xong rồi thử mở pull request đi

**Comment by VietDucc** [comment]
sao đặt tên nhánh ko có chức năng nhìn mọi người đặt theo, sao commit một người mà người khác comment

**Comment by SuperCoolGuy855** [comment]
@nguyenthiyenly0407 rebase lại với dev đi.

@VietDucc cũng rebase branch ông lại lun nha.

**Comment by VietDucc** [comment]
đã code gì đâu mà rebase
