### ISSUE TITLE
Thêm tính năng Auto login

### ISSUE THREAD

**Issue by ngodat0103** [ngodat0103/se347#40]
Thêm tính năng Auto login
Khi người dùng vô web, check cookie có token, nếu có thì redirect thẳng vô dashboard

_Originally posted by @ngodat0103 in https://github.com/ngodat0103/se347/issues/27#issuecomment-2526306041_

**Comment by SuperCoolGuy855** [comment]
Này chắc chỉ kiểm tra tại / thôi nhỉ?

**Comment by SuperCoolGuy855** [comment]
Với lại có cần kiểm tra token có valid ko nhỉ?

**Comment by ngodat0103** [comment]
t nghĩ là có 2 trường hợp, một là token đã expire rồi, decode cái jwt hình có có để time, check nếu hết hạn thì về login
Trường hợp thứ 2: token chưa hết hạn nhưng vẫn bị 401 do đã logout từ trước

**Comment by SuperCoolGuy855** [comment]
Trường hợp 1: Thì nếu hết hạn thì chắc sẽ vẫn để ở landing page, không redirect, còn nếu có và chưa hết hạn thì sẽ redirect sang dashboard.

Trường hợp 2: Kiểm tra với endpoint nào nhỉ?

**Comment by ngodat0103** [comment]
Cập nhật api hỗ trỡ kiểm tra token có hợp lệ hay không
https://github.com/ngodat0103/se347-backend/pull/23
> Trường hợp 2: Kiểm tra với endpoint nào nhỉ?
