### ISSUE TITLE
[Workspace-api]: add member

### ISSUE THREAD

**Issue by VietDucc** [ngodat0103/se347#47]

**Comment by VietDucc** [comment]
backend làm xong api nhắn liền nha, nên vẽ ra sơ đồ database trước, frontend có làm trước thì cũng dựa vô đó tự tạo api tự chạy luôn

**Comment by ngodat0103** [comment]
https://github.com/ngodat0103/se347-backend/pull/29
Check Pr, test thử xem ổn hết chưa

**Comment by ngodat0103** [comment]
Api backend đã có, close cái issue này
