### ISSUE TITLE
lỗi 500 ( internal server error ) 

### ISSUE THREAD

**Issue by nguyenthiyenly0407** [ngodat0103/se347#49]
Khi load lại trang dashboard thì hiện lỗi này
![z6128860199722_6b2e38cd406af58296c4eaa40912dbc5](https://github.com/user-attachments/assets/29a681a4-cdd6-4207-b462-0bd0940ae7d3)

**Comment by ngodat0103** [comment]
nhìn có vẻ log là của web server của frontend, debug/coi kĩ thử xem có cái nào liên quan đến call api bên phía backend không?

**Comment by ngodat0103** [comment]
Kiểm tra log của frontend á

**Comment by VietDucc** [comment]
load lại trang để làm gì, hiện workspace mới à

**Comment by nguyenthiyenly0407** [comment]
![4e9ffeff92b72fe976a6](https://github.com/user-attachments/assets/e61057a6-2429-4746-8bb9-cd13ba0c0e94)
![901d6c77073fba61e32e](https://github.com/user-attachments/assets/d098bbf1-a202-4efc-9c2b-997967f8e82d)
log của frontend nè

**Comment by ngodat0103** [comment]
@VietDucc  m check này đi. t nghĩ Ly nó đang branch cũ, chứ theo hình thì nó bảo file dashboard không tồn tại mà
Lỗi về phía frontend

**Comment by VietDucc** [comment]
này code cũ rồi
