### ISSUE TITLE
[Frontend]Thông báo lỗi cho tài khoản chưa đăng ký

### ISSUE THREAD

**Issue by VietDucc** [ngodat0103/se347#50]
![image](https://github.com/user-attachments/assets/ab087c3f-725b-460e-b10c-98e5ca28d8b2)
Hai bạn @ngocdiemm @nguyenthiyenly0407 thêm trường hợp người dùng chưa có tài khoản mà vẫn đăng nhập nhé

**Comment by ngodat0103** [comment]
Click vào POST để xem nó chứa body là gì đi

**Comment by nguyenthiyenly0407** [comment]
@VietDucc từ nha, quy trình của nó là mình chọn 1 tk bất kì nào đn vô, nó gửi request và phản hồi 404 là ko tìm thấy thì có gì sai đâu?

**Comment by VietDucc** [comment]
nó báo lỗi 404 thì sửa lại thông báo là tài khoản chưa tồn tại

**Comment by ngodat0103** [comment]
ý là cái đó cho dev biết, còn người dùng web thì have no idea sao web nó không phản hồi

> @VietDucc từ nha, quy trình của nó là mình chọn 1 tk bất kì nào đn vô, nó gửi request và phản hồi 404 là ko tìm thấy thì có gì sai đâu?

**Comment by nguyenthiyenly0407** [comment]
![image](https://github.com/user-attachments/assets/b9483db2-56ef-4f7f-b531-ba1bb0c021a0)
like this?

**Comment by VietDucc** [comment]
đúng rồi đổi lại thành tiếng anh

**Comment by ngodat0103** [comment]
xong rồi tạo PR thử, nếu merge thành công thì bên Đức phải rebase lại dev

**Comment by VietDucc** [comment]
từ nhánh vietduc/dashboard tạo một nhánh khác rồi merge vô ko tạo ra từ dev

**Comment by nguyenthiyenly0407** [comment]
@ngodat0103 @VietDucc  có cần tạo nhánh mới không

**Comment by VietDucc** [comment]
tạo nhánh mới từ vietduc fix cả hai lỗi luôn
