### ISSUE TITLE
Trình duyệt vẫn giữ cache cũ

### ISSUE THREAD

**Issue by VietDucc** [ngodat0103/se347#55]
![image](https://github.com/user-attachments/assets/6d8d00ca-9c60-407e-9cc0-81c2fedb940a)
Cần load lại url hoặc xóa cache cũ để có thể lấy ảnh vừa cập nhật về

**Comment by VietDucc** [comment]
nếu api trả về url khác thì trình duyệt sẻ tự động load ảnh mới, còn nếu api giữ nguyên thì ảnh sẻ lưu vào cache

**Comment by VietDucc** [comment]
@nguyenthiyenly0407  @ngocdiemm lo cái này hai đệ

**Comment by nguyenthiyenly0407** [comment]
@VietDucc mai t xem thử cái này, máy đang bị lag rồi.

**Comment by ngodat0103** [comment]
Khỏi fix, đợi cho nó hết cache cho xong
```node
 toast.success("Project updated successfully. For image changes need a few seconds to update.");
```

**Comment by VietDucc** [comment]
là sao

**Comment by nguyenthiyenly0407** [comment]
Là fix hay ko ấy

Vào 15:47, Th 4, 25 thg 12, 2024 Ngô Vũ Minh Đạt ***@***.***>
đã viết:
