### ISSUE TITLE
[Fronend:build]: Không build project được

### ISSUE THREAD

**Issue by SuperCoolGuy855** [ngodat0103/se347#60]
![image](https://github.com/user-attachments/assets/a8e1f6f6-a3bf-4d45-91a3-f7f94c405ece)

Sửa hết eslint error thì bị lỗi này, mà đọc không hiểu. Search code đâu thấy mình xài useSearchParams() đâu.

**Comment by VietDucc** [comment]
bun add next rồi bun run dev xem

**Comment by VietDucc** [comment]
ở dashboard xem có "use client" chưa

**Comment by SuperCoolGuy855** [comment]
> bun add next rồi bun run dev xem

Làm rồi mà cũng vẫn lỗi đó.

**Comment by SuperCoolGuy855** [comment]
> ở dashboard xem có "use client" chưa

![image](https://github.com/user-attachments/assets/5b91d368-f48b-41b8-a9eb-332ff82ff14d)

**Comment by SuperCoolGuy855** [comment]
Này không high priority đâu, rảnh thì coi qua.

**Comment by VietDucc** [comment]
xóa hết node_module chưa

**Comment by SuperCoolGuy855** [comment]
> xóa hết node_module chưa

Xoá node_modules và bun.lockb lun, vẫn ko đc

Coi thử chạy đc ko, cũng có thể máy t đang xàm

**Comment by VietDucc** [comment]
chạy được bth

**Comment by SuperCoolGuy855** [comment]
Ý là build á, chứ ko phải bun run dev. Chạy thử bun run build đi.

**Comment by ngodat0103** [comment]
> ![image](https://private-user-images.githubusercontent.com/29012883/396355701-a8e1f6f6-a3bf-4d45-91a3-f7f94c405ece.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0Mjg1NjAsIm5iZiI6MTczNDQyODI2MCwicGF0aCI6Ii8yOTAxMjg4My8zOTYzNTU3MDEtYThlMWY2ZjYtYTNiZi00ZDQ1LTkxYTMtZjdmOTRjNDA1ZWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA5Mzc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmM2MyYzM3NWM5ZjQxM2I0MzQ0Mzk0NmQ0M2Y2NjEyNjMzN2ViMTU1Zjg4OWFlMjQyOWU1MDJiMDA3MGJmM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Sdyh33hLoKHsytXOTVAaksETypvks6XEhHbNg2yBhIM)
> 
> Sửa hết eslint error thì bị lỗi này, mà đọc không hiểu. Search code đâu thấy mình xài useSearchParams() đâu.



```bash
akira@legion5:~/code/se347$ grep -r "useSearchParams" .
```
![image](https://github.com/user-attachments/assets/0674d9ad-8b08-49d7-84f6-297affcfadfa)
Cái useSearchParams() vẫn có, nó có depends trên package nuqs, chưa biết xử lý thế nào
![image](https://github.com/user-attachments/assets/3d2a4df6-b588-4c76-8901-63add742c0aa)

**Comment by VietDucc** [comment]
coi cái nào dùng useparam bọc lại bằng thẻ Suspense coi được kh

**Comment by VietDucc** [comment]
không thì thêm "use client" vô là được

**Comment by VietDucc** [comment]
sao t ko có lỗi đó nhỉ

**Comment by VietDucc** [comment]
build duoc chua

**Comment by ngodat0103** [comment]
Shit, code sai quy tắc, bad practice nên giờ hết build được rồi
![image](https://github.com/user-attachments/assets/bd460227-536e-48d0-bb71-3a55a6142f0c)

**Comment by SuperCoolGuy855** [comment]
> Shit, code sai quy tắc, bad practice nên giờ hết build được rồi ![image](https://private-user-images.githubusercontent.com/97928539/398446145-bd460227-536e-48d0-bb71-3a55a6142f0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NDUwOTIsIm5iZiI6MTczNTU0NDc5MiwicGF0aCI6Ii85NzkyODUzOS8zOTg0NDYxNDUtYmQ0NjAyMjctNTM2ZS00OGQwLWJiNzEtM2E1NWE2MTQyZjBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDA3NDYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmY2M1N2QyZDA4OGZmZWEzYjViMTYyZDcxNWE5MjY2YjZlMWVhMmExMGRmZTA0ZGVmNmZjODY2YjhmYjYwNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Fnai6dUbhHK5JgngihNV3JieMNzfvInzAqnO4VKV1ug)

Này nó ép naming convention thôi. Nếu không quan tâm thì có thể downgrade nó xuống warning.

**Comment by ngodat0103** [comment]
> > Shit, code sai quy tắc, bad practice nên giờ hết build được rồi ![image](https://private-user-images.githubusercontent.com/97928539/398446145-bd460227-536e-48d0-bb71-3a55a6142f0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NDUwOTIsIm5iZiI6MTczNTU0NDc5MiwicGF0aCI6Ii85NzkyODUzOS8zOTg0NDYxNDUtYmQ0NjAyMjctNTM2ZS00OGQwLWJiNzEtM2E1NWE2MTQyZjBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDA3NDYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmY2M1N2QyZDA4OGZmZWEzYjViMTYyZDcxNWE5MjY2YjZlMWVhMmExMGRmZTA0ZGVmNmZjODY2YjhmYjYwNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Fnai6dUbhHK5JgngihNV3JieMNzfvInzAqnO4VKV1ug)
> 
> Này nó ép naming convention thôi. Nếu không quan tâm thì có thể downgrade nó xuống warning.

Downgrade đi
