### ISSUE TITLE
Khi tạo workspace mới thành công, nên redirect ra lại dashboard, hoặc ra workspace mới được tạo

### ISSUE THREAD

**Issue by SuperCoolGuy855** [ngodat0103/se347#65]

**Comment by VietDucc** [comment]
lam roi

**Comment by VietDucc** [comment]
![image](https://github.com/user-attachments/assets/9f4bf625-2e05-4697-8410-af2d42386ac1)
khong biet push len chua vo nhanh vietduc xem
