### ISSUE TITLE
Dont comment backup

### ISSUE THREAD

**Issue by VietDucc** [ngodat0103/se347#66]
![image](https://github.com/user-attachments/assets/638f5472-6548-4919-ba65-dea9ea353cb5)
Làm trên nhánh mình thì ko cần comment, comment lại chi v

**Comment by VietDucc** [comment]
Fix lỗi nào thì auto tạo nhánh từ vietduc đừng tạo từ dev

**Comment by ngodat0103** [comment]
Xử lí rồi nha
https://github.com/ngodat0103/se347/pull/57
