### ISSUE TITLE
[Fronend:create-project]: createProjectForm sau khi tạo form thành công, không đóng form

### ISSUE THREAD

**Issue by ngodat0103** [ngodat0103/se347#69]

**Comment by VietDucc** [comment]
cái này lấy component của cái tạo wp đúng ko, t có sửa ở trong cái tạo wp r

**Comment by VietDucc** [comment]
![image](https://github.com/user-attachments/assets/a037bf06-dfef-4db2-899e-1b52bb41fb8a)
đã làm nhé
