### ISSUE TITLE
[Fronend:create-project]: thiếu tính năng cập nhật ảnh

### ISSUE THREAD

**Issue by ngodat0103** [ngodat0103/se347#70]

**Comment by SuperCoolGuy855** [comment]
Thiếu tính năng cập nhật ảnh của gì? User hả?

**Comment by ngodat0103** [comment]
cập nhật ảnh của project, đã có UI component của nó, mà lười làm, khá giống việc upload ảnh của workspace

**Comment by VietDucc** [comment]
mai lam cho
