### ISSUE TITLE
Kiểm tra nhầm kiểu

### ISSUE THREAD

**Issue by VietDucc** [ngodat0103/se347#74]
![image](https://github.com/user-attachments/assets/c8784f43-78c6-4a9a-a993-3ea7dcaae22b)
![image](https://github.com/user-attachments/assets/6d91ac6b-bdf4-4900-a73c-dd121e70dff6)
- Chuyện là hôm nay khi tôi ngủ dậy và hoàn thành khóa react hook, tôi đã tiếp tục làm jira cờ lon, nhưng 
- chỗ swagger thêm người dùng là lấy wd id và email nhưng token của người mời, nhưng làm theo cách của thằng atoni thì NGƯỜI ĐƯỢC MỜI phải đăng nhập vô và accept cái link đó nên cái token của người mời
-> Phương án: Đề nghị xem lại phần token ko nên kiểm tra phần token và email được gửi lên có trùng nhau hay ko, mà nên kiểm tra email chỉ cần có ở trong wp đó hay chưa thôi @ngodat0103

**Comment by VietDucc** [comment]
- Nếu có thời gian làm cái accept bằng cách gửi email về thì dùng api đó, còn giờ ko có thời gian đổi lại đi

**Comment by ngodat0103** [comment]
Sử dụng nhầm api
- cái api add by Email là cho owner của workspace
- người khác gia nhập thì browser phải call api khác
Tìm hiểu và sử dụng api join
![image](https://github.com/user-attachments/assets/16b81d17-fce0-45d4-af5a-940fdf7cdf0a)

**Comment by ngodat0103** [comment]
Chi tiết luồn cho tính năng này
https://github.com/ngodat0103/se347-backend/pull/33

**Comment by VietDucc** [comment]
à ok ko nói m

**Comment by ngodat0103** [comment]
do không check pr bên backend á, t invite m rồi, k xem chi
