### ISSUE TITLE
[Backend]: Cố định thứ tự danh sách workspaces

### ISSUE THREAD

**Issue by SuperCoolGuy855** [ngodat0103/se347#81]
Thứ tự của các workspace trong danh sách thay đổi liên tục khi refresh page, làm rối user.

https://github.com/user-attachments/assets/906aaae8-5a02-4cb6-908b-df4e48d7e1d4

**Comment by ngodat0103** [comment]
Thêm default sort query cho api, đã set giá trị default sortField=name, sortOrder=ASC
frontend không cần làm gì
![image](https://github.com/user-attachments/assets/2cd92428-3102-4f4b-93e5-c9c4073fe9a3)

Check backend PR: 
https://github.com/ngodat0103/se347-backend/pull/37
