### ISSUE TITLE
[Fronend:joinByInviteCode]: Join workspace lại hiển thị invite code chứ ko phải tên workspace

### ISSUE THREAD

**Issue by SuperCoolGuy855** [ngodat0103/se347#84]
![image](https://github.com/user-attachments/assets/2606e81c-1ff6-4f02-8291-b72167e98de8)

**Comment by ngodat0103** [comment]
@VietDucc 
![image](https://github.com/user-attachments/assets/4304c1d2-fdfc-4551-8fc6-05d034a8bbd3)
Dùng api này để lấy thông tin workspace trước rồi mới hiện thi tên cho user

**Comment by VietDucc** [comment]
biết mà lười làm

**Comment by VietDucc** [comment]
![image](https://github.com/user-attachments/assets/4ac94855-e9b1-42b7-b6e8-4bfdc0b6587e)
done!
