### ISSUE TITLE
[Backend]: Cố định thứ tự danh sách member

### ISSUE THREAD

**Issue by SuperCoolGuy855** [ngodat0103/se347#85]
https://github.com/user-attachments/assets/256658e9-9eb6-485f-95ba-eb6a112da117

**Comment by ngodat0103** [comment]
Với Member thì t để default là sort ưu tiên theo thứ tự sau 
role -> name
sắp xếp tăng dần
https://github.com/ngodat0103/se347-backend/pull/37
