### ISSUE TITLE
[Frontend:invite-link]: Invite link không hợp lý

### ISSUE THREAD

**Issue by SuperCoolGuy855** [ngodat0103/se347#86]
Invite link phải nên là: `http://localhost:4200/join/<inviteCode>`

Chứ ko phải là: `http://localhost:4200/workspaces/<workspaceID>/join/<inviteCode>`

**Comment by VietDucc** [comment]
kệ đi để lấy cái workspace id, bỏ qua cái này ko cần fix

**Comment by VietDucc** [comment]
làm xong tính
