### ISSUE TITLE
[Fronend:project-setting]: Nên thoát form và refresh lại data sau khi update project setting

### ISSUE THREAD

**Issue by ngodat0103** [ngodat0103/se347#92]
thêm ảnh và chỉnh sửa ok, mà lại thiếu thoát form và refresh lại trang, tạo issue fix sau

_Originally posted by @ngodat0103 in https://github.com/ngodat0103/se347/pull/91#pullrequestreview-2520060942_

**Comment by VietDucc** [comment]
https://github.com/user-attachments/assets/3a98dc5c-706b-4028-bc1f-1639a730f99a

Fix rồi nha

**Comment by VietDucc** [comment]
Uploading 2024-12-24 10-58-19.mp4…
