### ISSUE TITLE
[Frontend:task-table]:  Date bị conflict

### ISSUE THREAD

**Issue by ngodat0103** [ngodat0103/se347#93]
load date bị conflict time, sẽ tạo issue fix sau
_Originally posted by @ngodat0103 in https://github.com/ngodat0103/se347/issues/79#issuecomment-2558408122_

**Comment by VietDucc** [comment]
đã fix

**Comment by ngodat0103** [comment]
> đã fix

Ok, tạo branch và link issue này tới branch đó

**Comment by VietDucc** [comment]
nằm trong branch vietduc/kanban luôn r
