### ISSUE TITLE
[Backend::set-task]: Set quyền chỉnh cho member

### ISSUE THREAD

**Issue by VietDucc** [ngodat0103/se347#96]
![image](https://github.com/user-attachments/assets/b8317214-49ea-4e19-ba26-adadea17fd90)
- Member phải có quyền chỉnh task để mỗi lần làm xong member tự chỉnh

**Comment by ngodat0103** [comment]
![image](https://github.com/user-attachments/assets/79c93fcb-e587-4299-99c6-7d57812a7ad6)

T có thêm role Developer, thử chỉnh bên phía Frontend xem sao


Với lại cũng nên thông báo user không đủ quyển nữa

**Comment by VietDucc** [comment]
![image](https://github.com/user-attachments/assets/326b00c7-4b77-4ef0-85c2-522ca5fd347c)
tạo task được mà ko chỉnh task được

**Comment by ngodat0103** [comment]
> ![image](https://private-user-images.githubusercontent.com/169456748/398525289-326b00c7-4b77-4ef0-85c2-522ca5fd347c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMTI0MzEsIm5iZiI6MTczNTExMjEzMSwicGF0aCI6Ii8xNjk0NTY3NDgvMzk4NTI1Mjg5LTMyNmIwMGM3LTRiNzctNGVmMC04NWMyLTUyMmNhNWZkMzQ3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNVQwNzM1MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTgyOGRlNmUxNzU2ODAxYTljYWMxNDVhNDYxOGYzYmI1OTBmMjQwYWYwMWQzOGEyODQ5MWE1MzgxODBmYjQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wfGgj-IPyctMyFmdOVqg2RjsEukOgDL3Bm4dFwKEKkw) tạo task được mà ko chỉnh task được
Đã chỉnh role qua Developer chưa

**Comment by Crypto347** [comment]
ok được rồi nhé
có admin developer với member nha: admin có quyền chỉnh sửa xóa, deve được tạo và chỉnh xóa task, member được nhìn đúng ko @ngodat0103

**Comment by VietDucc** [comment]
ok được rồi nhé
có admin developer với member nha: admin có quyền chỉnh sửa xóa, deve được tạo và chỉnh xóa task, member được nhìn đúng ko @ngodat0103
